server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url:  jdbc:mysql://database-1.cjj2kmz38fzs.ap-northeast-2.rds.amazonaws.com/Young_Thinking?autoReconnect=true # 변경해주세요
    username:  rlckdrkdud
    password:  rlckd159
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    #com.mysql.jdbc.Driver
    # driver-class-name: com.mysql.cj.jdbc.Driver # mysql 5버전
  # url: jdbc:mysql://developerhyun.cyid0j45jyim.ap-northeast-2.rds.amazonaws.com/cupang_eats?autoReconnect=true # 변경해주세요
  #    username: rlckdrkdud # 변경해주세요
  #    password: rlckd159 # 변경해주세요
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect


    show-sql: false

    hibernate.ddl-auto: create